# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            '129 Studios'
tagline:          ''
description:      'A small indie studio from the Netherlands.'
url:              https://129-studios.github.io
baseurl:          /

author:
  name:           'Erik van den Bergh'
  url:            https://instagram.com/129gamestudios

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/129-Studios/129-studios.github.io
